version: '3'

services:
  webapp:
    build: .
    image: boaweb/engine-ai
    container_name: 'BOA-ENGINE-AI'
    restart: always
    command: ./docker/docker-entrypoint.sh
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-size: '100m'
        max-file: '7'
    ports:
      - '3040:3000'
    volumes:
      - '.:/boa_ai_engine'
